import React, { useState, useEffect, useCallback } from 'react';
import { Box, CircularProgress, IconButton, Tooltip, Chip, Button, Checkbox } from '@mui/material';
import { MdRefresh } from 'react-icons/md';
import { TableSection, TableTitle, TableWrapper, Table } from './SectorOutlook.styles';
import { fetchWeeklyPicks, triggerWeeklyPicks, generateWeeklyPicks } from '../api/stocks';
import { addToWatchlist } from '../api/watchlist';

const gradeColor = { A: '#1b5e20', B: '#2e7d32', C: '#f57f17', D: '#c62828' };
const gradeBg = { A: '#e8f5e9', B: '#f1f8e9', C: '#fff8e1', D: '#ffebee' };
const compact = { fontSize: 11, padding: '4px 5px', whiteSpace: 'nowrap' };

function normalizePickTargets(row, isBullish) {
  const entry = Number(row?.entry_price);
  const sl = Number(row?.stop_loss);
  let t1 = Number(row?.target_1);
  let t2 = Number(row?.target_2);
  if (!Number.isFinite(entry) || !Number.isFinite(sl)) return row;
  if (!Number.isFinite(t1)) return row;
  if (!Number.isFinite(t2)) t2 = t1;
  const risk = Math.abs(entry - sl);
  const minGap = Math.max(risk * 1.5, entry * 0.02);
  if (isBullish && t2 <= t1) t2 = t1 + minGap;
  if (!isBullish && t2 >= t1) t2 = t1 - minGap;
  return { ...row, target_1: t1, target_2: t2 };
}

function computeRRTargets(row, isBullish) {
  const entry = Number(row?.entry_price);
  const sl = Number(row?.stop_loss);
  if (!Number.isFinite(entry) || !Number.isFinite(sl) || entry <= 0) {
    return { risk: null, t4r: null, t6r: null, t10r: null, t4r_pct: null, t6r_pct: null, t10r_pct: null };
  }
  const risk = Math.abs(entry - sl);
  if (!(risk > 0)) {
    return { risk: null, t4r: null, t6r: null, t10r: null, t4r_pct: null, t6r_pct: null, t10r_pct: null };
  }
  const sign = isBullish ? 1 : -1;
  return {
    risk,
    t4r: entry + sign * 4 * risk,
    t6r: entry + sign * 6 * risk,
    t10r: entry + sign * 10 * risk,
    t4r_pct: sign * 4 * risk / entry * 100,
    t6r_pct: sign * 6 * risk / entry * 100,
    t10r_pct: sign * 10 * risk / entry * 100,
  };
}

function AiPicksPage() {
  const [data, setData] = useState({ bullish: [], bearish: [], fno_bullish: [], fno_bearish: [], pick_date: null });
  const [loading, setLoading] = useState(true);
  const [triggering, setTriggering] = useState(false);
  const [error, setError] = useState(null);
  const [added, setAdded] = useState({});
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [checkedSymbols, setCheckedSymbols] = useState(new Set());

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const resp = await fetchWeeklyPicks();
      setData({
        bullish: resp?.bullish ?? [],
        bearish: resp?.bearish ?? [],
        fno_bullish: resp?.fno_bullish ?? [],
        fno_bearish: resp?.fno_bearish ?? [],
        pick_date: resp?.pick_date ?? null,
      });
      return resp;
    } catch (e) {
      setError(e?.message || 'Failed to load weekly picks');
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    let cancelled = false;
    const init = async () => {
      const resp = await load();
      if (cancelled) return;
      const empty = (!resp?.bullish?.length && !resp?.bearish?.length);
      if (empty && !autoGenerated) {
        setAutoGenerated(true);
        setTriggering(true);
        try {
          await generateWeeklyPicks();
          if (!cancelled) await load();
        } catch (_) { /* ignore */ }
        if (!cancelled) setTriggering(false);
      }
    };
    init();
    return () => { cancelled = true; };
  }, [load, autoGenerated]);

  const handleTrigger = async () => {
    setTriggering(true);
    try {
      await generateWeeklyPicks();
      await load();
    } catch (_) {
      try {
        await triggerWeeklyPicks();
        await new Promise(r => setTimeout(r, 3000));
        await load();
      } catch (_2) { /* ignore */ }
    }
    setTriggering(false);
  };

  const handleAdd = async (symbol, listType) => {
    const key = `${symbol}_${listType}`;
    if (added[key]) return;
    try {
      await addToWatchlist(symbol.toUpperCase(), listType, '');
      setAdded(prev => ({ ...prev, [key]: true }));
    } catch (_) { /* ignore */ }
  };

  const handleAddSelected = async (listType) => {
    const syms = [...checkedSymbols].filter(Boolean);
    for (const symbol of syms) {
      // eslint-disable-next-line no-await-in-loop
      await handleAdd(symbol, listType);
    }
  };

  const fmt = (v, decimals = 2) => {
    if (v == null) return '—';
    return `₹${Number(v).toLocaleString('en-IN', { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}`;
  };

  const renderTable = (rows, type, titleOverride) => {
    const isBullish = type === 'bullish';
    const headerBg = isBullish ? '#1b5e20' : '#b71c1c';
    const title = titleOverride || (isBullish ? 'Bullish Swing Picks' : 'Bearish Swing Picks');

    return (
      <TableSection style={{ marginTop: 0 }}>
        <TableTitle style={{ color: headerBg, fontSize: 16 }}>{title}</TableTitle>
        <TableWrapper>
          <Table style={{ fontSize: 11 }}>
            <thead style={{ backgroundColor: headerBg }}>
              <tr>
                <th style={compact}>#</th>
                <th style={compact}>Symbol</th>
                <th style={compact}>Grade</th>
                <th style={compact}>CMP</th>
                <th style={compact}>Entry</th>
                <th style={compact}>SL</th>
                <th style={compact}>SL%</th>
                <th style={compact}>T1</th>
                <th style={compact}>T2</th>
                <th style={{ ...compact, background: 'rgba(255,255,255,0.15)' }}>T 4R</th>
                <th style={{ ...compact, background: 'rgba(255,255,255,0.2)' }}>T 6R</th>
                <th style={{ ...compact, background: 'rgba(255,255,255,0.25)' }}>T 10R</th>
                <th style={compact}>Reco</th>
                <th style={compact}>
                  <Checkbox
                    size="small"
                    checked={rows.length > 0 && rows.every((r) => checkedSymbols.has(r.symbol))}
                    indeterminate={rows.some((r) => checkedSymbols.has(r.symbol)) && !rows.every((r) => checkedSymbols.has(r.symbol))}
                    onChange={() => {
                      const rowSyms = rows.map((r) => r.symbol).filter(Boolean);
                      const allSelected = rowSyms.length > 0 && rowSyms.every((s) => checkedSymbols.has(s));
                      setCheckedSymbols((prev) => {
                        const next = new Set(prev);
                        if (allSelected) rowSyms.forEach((s) => next.delete(s));
                        else rowSyms.forEach((s) => next.add(s));
                        return next;
                      });
                    }}
                  />
                </th>
              </tr>
            </thead>
            <tbody>
              {rows.length === 0 && (
                <tr>
                  <td colSpan={14} style={{ textAlign: 'center', padding: 24, color: '#888' }}>
                    No {type} picks available yet. Run the analysis to generate picks.
                  </td>
                </tr>
              )}
              {rows.map((r, i) => {
                const pick = normalizePickTargets(r, isBullish);
                const rr = computeRRTargets(pick, isBullish);
                return (
                  <tr key={r.symbol}>
                    <td style={{ ...compact, fontWeight: 600, color: '#888' }}>{String(i + 1).padStart(2, '0')}</td>
                    <td style={{ ...compact, fontWeight: 700 }}>
                      {r.symbol}
                      {r.is_fno && (
                        <span style={{
                          marginLeft: 3, fontSize: 8, padding: '1px 3px', borderRadius: 2,
                          background: '#0d47a1', color: '#fff', fontWeight: 600, verticalAlign: 'super'
                        }}>F&O</span>
                      )}
                    </td>
                    <td style={compact}>
                      <span style={{
                        display: 'inline-block', padding: '1px 8px', borderRadius: 3,
                        fontWeight: 700, fontSize: 11,
                        color: gradeColor[r.grade] || '#333',
                        background: gradeBg[r.grade] || '#f5f5f5',
                      }}>
                        {r.grade}
                      </span>
                    </td>
                    <td style={{ ...compact, fontWeight: 600 }}>{fmt(r.cmp)}</td>
                    <td style={{ ...compact, fontWeight: 600, color: '#1565c0' }}>{fmt(r.entry_price)}</td>
                    <td style={{ ...compact, color: '#c62828' }}>{fmt(r.stop_loss)}</td>
                    <td style={{ ...compact, color: (r.sl_pct && r.sl_pct < 3) ? '#2e7d32' : '#c62828', fontSize: 10 }}>
                      {r.sl_pct != null ? `${Number(r.sl_pct).toFixed(1)}%` : '—'}
                    </td>
                    <td style={{ ...compact, color: isBullish ? '#2e7d32' : '#c62828', fontWeight: 600 }}>{fmt(pick.target_1)}</td>
                    <td style={{ ...compact, color: isBullish ? '#2e7d32' : '#c62828', fontWeight: 600 }}>{fmt(pick.target_2)}</td>
                    <td style={{ ...compact, background: '#e3f2fd', fontWeight: 700, color: '#0d47a1' }}>
                      {rr.t4r != null ? fmt(rr.t4r) : '—'}
                      {rr.t4r_pct != null && <span style={{ fontSize: 9, marginLeft: 1, opacity: 0.7 }}>({rr.t4r_pct.toFixed(1)}%)</span>}
                    </td>
                    <td style={{ ...compact, background: '#e8eaf6', fontWeight: 700, color: '#283593' }}>
                      {rr.t6r != null ? fmt(rr.t6r) : '—'}
                      {rr.t6r_pct != null && <span style={{ fontSize: 9, marginLeft: 1, opacity: 0.7 }}>({rr.t6r_pct.toFixed(1)}%)</span>}
                    </td>
                    <td style={{ ...compact, background: '#ede7f6', fontWeight: 700, color: '#4a148c' }}>
                      {rr.t10r != null ? fmt(rr.t10r) : '—'}
                      {rr.t10r_pct != null && <span style={{ fontSize: 9, marginLeft: 1, opacity: 0.7 }}>({rr.t10r_pct.toFixed(1)}%)</span>}
                    </td>
                    <td style={compact}>
                      <Chip
                        label={(r.recommendation || '—').toUpperCase()}
                        size="small"
                        sx={{
                          fontWeight: 700, fontSize: 10, height: 20,
                          bgcolor: r.recommendation?.includes('buy') ? '#e8f5e9'
                            : r.recommendation?.includes('sell') ? '#ffebee' : '#f5f5f5',
                          color: r.recommendation?.includes('buy') ? '#1b5e20'
                            : r.recommendation?.includes('sell') ? '#b71c1c' : '#333',
                        }}
                      />
                    </td>
                    <td style={compact}>
                      <Checkbox
                        size="small"
                        checked={checkedSymbols.has(r.symbol)}
                        onChange={() => {
                          setCheckedSymbols((prev) => {
                            const next = new Set(prev);
                            if (next.has(r.symbol)) next.delete(r.symbol);
                            else next.add(r.symbol);
                            return next;
                          });
                        }}
                      />
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </Table>
        </TableWrapper>
      </TableSection>
    );
  };

  const renderSwingPlan = (rows) => {
    if (!rows.length) return null;
    return (
      <Box sx={{ mt: 2, p: 2, bgcolor: '#f8f9fa', borderRadius: 2, border: '1px solid #e0e0e0' }}>
        <Box sx={{ fontWeight: 700, fontSize: 14, mb: 1, color: '#1a3c5e' }}>
          Swing Trade Pyramiding Plan (3-6 Weeks) — Buy Side Only
        </Box>
        <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 2 }}>
          {rows.map(r => {
            const pick = normalizePickTargets(r, true);
            const rr = computeRRTargets(pick, true);
            if (!pick.entry_price || !pick.stop_loss || !rr.risk) return null;
            return (
              <Box key={r.symbol} sx={{ p: 1.5, bgcolor: '#fff', borderRadius: 1, border: '1px solid #e0e0e0' }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                  <span style={{ fontWeight: 700, fontSize: 14 }}>{r.symbol}</span>
                  <Chip label={r.grade} size="small"
                    sx={{ fontWeight: 700, fontSize: 11, color: gradeColor[r.grade], bgcolor: gradeBg[r.grade] }} />
                </Box>
                <Box sx={{ fontSize: 12, lineHeight: 1.8 }}>
                  <Box><span style={{ color: '#888', width: 90, display: 'inline-block' }}>Risk per share:</span>
                    <strong style={{ color: '#c62828' }}>₹{rr.risk?.toFixed(2)}</strong>
                    <span style={{ color: '#888', fontSize: 10, marginLeft: 4 }}>({pick.sl_pct?.toFixed(1)}%)</span>
                  </Box>
                  <Box sx={{ mt: 0.5, pl: 1, borderLeft: '3px solid #1565c0' }}>
                    <Box><strong>1.</strong> Enter at <strong style={{ color: '#1565c0' }}>{fmt(r.entry_price)}</strong>, SL at <strong style={{ color: '#c62828' }}>{fmt(r.stop_loss)}</strong></Box>
                    <Box><strong>2.</strong> Price moves above T1 <strong style={{ color: '#2e7d32' }}>{fmt(pick.target_1)}</strong> → trail SL to entry (risk-free)</Box>
                    <Box><strong>3.</strong> Add at T1, new SL at entry → <strong style={{ color: '#0d47a1' }}>T 4R {fmt(rr.t4r)}</strong>
                      <span style={{ fontSize: 10, color: '#888' }}> (+{rr.t4r_pct?.toFixed(1)}%)</span></Box>
                    <Box><strong>4.</strong> Add at T2 <strong>{fmt(pick.target_2)}</strong> → <strong style={{ color: '#283593' }}>T 6R {fmt(rr.t6r)}</strong>
                      <span style={{ fontSize: 10, color: '#888' }}> (+{rr.t6r_pct?.toFixed(1)}%)</span></Box>
                    <Box><strong>5.</strong> Hold runners → <strong style={{ color: '#4a148c' }}>T 10R {fmt(rr.t10r)}</strong>
                      <span style={{ fontSize: 10, color: '#888' }}> (+{rr.t10r_pct?.toFixed(1)}%)</span></Box>
                  </Box>
                </Box>
              </Box>
            );
          })}
        </Box>
      </Box>
    );
  };

  return (
    <div>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
        <Box>
          <h2 style={{ margin: 0, fontSize: 22, fontWeight: 800, color: '#0b3d91' }}>
            Weekly AI Picks — Swing Trade Setup
          </h2>
          <span style={{ fontSize: 12, color: '#666' }}>
            {data.pick_date ? `Generated: ${data.pick_date}` : ''}
            {' · '}Targets: 4R / 6R / 10R for pyramiding (3-6 week swing)
          </span>
        </Box>
        <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
          <Button size="small" variant="contained" disabled={checkedSymbols.size === 0} onClick={() => handleAddSelected('short_term')} sx={{ textTransform: 'none' }}>
            {`Add ST (${checkedSymbols.size})`}
          </Button>
          <Button size="small" variant="contained" disabled={checkedSymbols.size === 0} onClick={() => handleAddSelected('long_term')} sx={{ textTransform: 'none', bgcolor: '#2e7d32' }}>
            {`Add LT (${checkedSymbols.size})`}
          </Button>
          <Tooltip title="Refresh picks">
            <IconButton onClick={load} size="small"><MdRefresh size={20} /></IconButton>
          </Tooltip>
          <Tooltip title="Generate picks now">
            <span>
              <IconButton onClick={handleTrigger} disabled={triggering} size="small"
                sx={{ bgcolor: '#e3f2fd', '&:hover': { bgcolor: '#bbdefb' } }}>
                {triggering ? <CircularProgress size={18} /> : <MdRefresh size={20} color="#1565c0" />}
              </IconButton>
            </span>
          </Tooltip>
        </Box>
      </Box>

      {loading && (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}><CircularProgress /></Box>
      )}

      {error && <div style={{ color: '#dc3545', fontWeight: 600, marginBottom: 16 }}>{error}</div>}

      {!loading && !error && (
        <>
          <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: '1fr 1fr' }, gap: 2 }}>
            {renderTable(data.bullish, 'bullish')}
            {renderTable(data.bearish, 'bearish')}
          </Box>
          {renderSwingPlan(data.bullish)}

          {(data.fno_bullish?.length > 0 || data.fno_bearish?.length > 0) && (
            <Box sx={{ mt: 4 }}>
              <Box sx={{
                display: 'flex', alignItems: 'center', gap: 1.5, mb: 2,
                pb: 1, borderBottom: '2px solid #1565c0'
              }}>
                <Box sx={{
                  px: 1.5, py: 0.3, bgcolor: '#0d47a1', color: '#fff',
                  fontWeight: 800, fontSize: 13, borderRadius: 1, letterSpacing: 0.5
                }}>
                  F&O
                </Box>
                <h3 style={{ margin: 0, fontSize: 18, fontWeight: 700, color: '#0d47a1' }}>
                  Futures & Options — Swing Picks
                </h3>
                <span style={{ fontSize: 11, color: '#888' }}>
                  (Stocks available for derivatives trading on NSE)
                </span>
              </Box>
              <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: '1fr 1fr' }, gap: 2 }}>
                {renderTable(data.fno_bullish, 'bullish', 'F&O Bullish Picks')}
                {renderTable(data.fno_bearish, 'bearish', 'F&O Bearish Picks')}
              </Box>
              {renderSwingPlan(data.fno_bullish)}
            </Box>
          )}
        </>
      )}

      {!loading && !error && data.bullish.length === 0 && data.bearish.length === 0 && !triggering && (
        <Box sx={{ textAlign: 'center', py: 6, color: '#888', border: '2px dashed #e0e0e0', borderRadius: 2, mt: 2 }}>
          <p style={{ fontSize: 16, margin: 0 }}>No weekly picks available yet.</p>
          <p style={{ fontSize: 14, margin: '8px 0 0', color: '#aaa' }}>
            Picks are generated automatically every Saturday at 2:00 AM, or click the refresh button to trigger manually.
          </p>
        </Box>
      )}

      {triggering && !loading && (
        <Box sx={{ textAlign: 'center', py: 4, color: '#1565c0', border: '2px dashed #bbdefb', borderRadius: 2, mt: 2, bgcolor: '#e3f2fd' }}>
          <CircularProgress size={24} sx={{ mb: 1 }} />
          <p style={{ fontSize: 14, margin: '8px 0 0' }}>Generating AI picks from latest ratings data...</p>
        </Box>
      )}
    </div>
  );
}

export default AiPicksPage;
